" -------------------------------- "
"         General
" -------------------------------- "
set nocompatible
set encoding=utf-8
set fileencoding=utf-8
set backspace=indent,eol,start
set hidden
set number
set showmatch
set cursorline
set colorcolumn=100
set splitright
set splitbelow
set wildmenu
set wildmode=list:longest
set hlsearch
set incsearch
set ignorecase
set smartcase
set scrolloff=5
set updatetime=300

" Strip trailing whitespace on save
augroup trim_trailing_ws
  autocmd!
  autocmd BufWritePre * %s/\s\+$//e
augroup END

" -------------------------------- "
"         Indentation
" -------------------------------- "
set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set foldmethod=indent

filetype plugin indent on

autocmd FileType html setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType yaml setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType json setlocal shiftwidth=2 tabstop=2 softtabstop=2
autocmd FileType sql setlocal shiftwidth=2 tabstop=2 softtabstop=2

" -------------------------------- "
"         Filetype tweaks
" -------------------------------- "
let g:sql_type_default = 'pgsql'
autocmd FileType sql setlocal commentstring=--\ %s
au BufReadPost *.html set filetype=html
au! BufNewFile,BufRead *.s3cfg setf dosini
au! BufNewFile,BufRead env.dist* setf sh
au BufRead,BufNewFile *.ini.template set filetype=dosini
au BufRead,BufNewFile *.yml.template set filetype=yaml
au BufRead,BufNewFile *.aws/credentials set filetype=dosini
au BufRead,BufNewFile nginx*.conf set filetype=nginx
au BufRead,BufNewFile .X* set filetype=xdefaults
au BufRead,BufNewFile .ghci set filetype=haskell

" -------------------------------- "
"         Colors
" -------------------------------- "
if &t_Co < 256
  set t_Co=256
endif

syntax on

if filereadable(expand("~/.vim/colors/molokai.vim"))
  colorscheme molokai
else
  colorscheme default
endif

highlight Comment cterm=italic

" Python self highlight (Vim only).
if !has('nvim')
  " Define and re-apply the match after syntax/colorscheme resets.
  function! s:python_self_apply() abort
    if &filetype !=# 'python'
      return
    endif
    syntax keyword pythonSelf self
    highlight pythonSelf cterm=bold ctermfg=208 gui=bold guifg=#FD971F
  endfunction

  augroup python_self_highlight
    autocmd!
    " Catch first buffer and later Python buffers.
    autocmd VimEnter * call <SID>python_self_apply()
    autocmd BufWinEnter *.py call <SID>python_self_apply()
    " Restore match after syntax/colorscheme reloads.
    autocmd Syntax python call <SID>python_self_apply()
    autocmd ColorScheme * call <SID>python_self_apply()
  augroup END
endif

" Python self highlight (Vim only; keep minimal and explicit).

" -------------------------------- "
"         Status line
" -------------------------------- "
set laststatus=2
hi StatusLineMode   ctermfg=231 ctermbg=24  cterm=bold
hi StatusLineFile   ctermfg=231 ctermbg=236 cterm=none
hi StatusLineInfo   ctermfg=250 ctermbg=234 cterm=none
hi StatusLinePos    ctermfg=231 ctermbg=238 cterm=bold
hi StatusLineSep    ctermfg=240 ctermbg=234 cterm=none

set statusline=
set statusline+=%#StatusLineMode#\ %{mode()}\ 
set statusline+=%#StatusLineSep#\|\ 
set statusline+=%#StatusLineFile#%f\ %m%r%h%w\ 
set statusline+=%#StatusLineSep#\|\ 
set statusline+=%#StatusLineInfo#[%{&filetype}]\ [%{&fileencoding?&fileencoding:'none'}]\ 
set statusline+=%=
set statusline+=%#StatusLinePos#%l:%c\ %p%%\ 

" -------------------------------- "
"         Local overrides
" -------------------------------- "
if filereadable(expand("~/.vimrc.local"))
  source ~/.vimrc.local
endif
