##############################
# Modular zsh config
##############################
config_home="${XDG_CONFIG_HOME:-$HOME/.config}"
conf_dir="$config_home/zsh/conf.d"

if [[ ! -d "$conf_dir" ]]; then
    zshrc_dir="${${(%):-%N}:A:h}"
    conf_dir="$zshrc_dir/conf.d"
fi

if [[ -d "$conf_dir" ]]; then
    for file in "$conf_dir"/*.zsh(N); do
        # shellcheck disable=SC1090
        source "$file"
    done
fi
